server:
  port: 8081
spring:
  application:
    name: dialing-robot-web
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dialing_robot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8mb4&useSSL=false&allowMultiQueries=true
    username: root
    password: liu199836
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: dialing-robot-web
  config-center:
    enabled: false
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: cn.lxm.core.service
  qos:
    enable: false
    port: -1
  metadata-report:
    file-cache: false